[build]
  command = "bash netlify-build.sh"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones prioritarias para artículos del blog con problemas
[[redirects]]
  from = "/balanceo-de-lineas-optimizando-la-eficiencia-en-procesos-de-manufactura*"
  to = "/es/blog/balanceo-de-lineas-optimizando-la-eficiencia-en-procesos-de-manufactura/"
  status = 301
  force = true

[[redirects]]
  from = "/calculo-de-saturacion-en-un-estudio-de-tiempos*"
  to = "/es/blog/calculo-de-saturacion-en-un-estudio-de-tiempos/"
  status = 301
  force = true

[[redirects]]
  from = "/que-es-el-cronometraje-industrial*"
  to = "/es/blog/que-es-el-cronometraje-industrial/"
  status = 301
  force = true

[[redirects]]
  from = "/cuales-son-las-tecnicas-de-cronometraje-industrial*"
  to = "/es/blog/cuales-son-las-tecnicas-de-cronometraje-industrial/"
  status = 301
  force = true

[[redirects]]
  from = "/optimizacion-de-sistemas-productivos-clave-para-la-eficiencia-industrial*"
  to = "/es/blog/optimizacion-de-sistemas-productivos-clave-para-la-eficiencia-industrial/"
  status = 301
  force = true

# Redirección genérica para artículos del blog (excluyendo la URL principal y otras rutas importantes)
[[redirects]]
  from = "/:article*"
  to = "/es/blog/:article/"
  status = 301
  force = true
  conditions = {Path = {exclude = ["/", "/es/", "/en/", "/es/blog/*", "/en/blog/*", "/es/features/*", "/en/features/*", "/es/about/*", "/en/about/*", "/es/contact/*", "/en/contact/*", "/es/faq/*", "/en/faq/*", "/es/terms/*", "/en/terms/*", "/es/privacy/*", "/en/privacy/*", "/es/method/*", "/en/method/*", "/es/dashboard/*", "/en/dashboard/*", "/es/repetitive/*", "/en/repetitive/*", "/es/continuous/*", "/en/continuous/*", "/es/machine/*", "/en/machine/*", "/es/supplements/*", "/en/supplements/*", "/es/report/*", "/en/report/*", "/es/library/*", "/en/library/*", "/es/screens/*", "/en/screens/*", "/es/info/*", "/en/info/*", "/es/frequency/*", "/en/frequency/*"]}}

# Redirección genérica para cualquier lección
[[redirects]]
  from = "/leccion/:lesson*"
  to = "/es/blog/:lesson/"
  status = 301
  force = true

# Redirecciones para manejar rutas con lenguaje
[[redirects]]
  from = "/"
  to = "/es/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es/"
  status = 302
  force = true

# Redirecciones para páginas específicas
[[redirects]]
  from = "/about"
  to = "/es/about/"
  status = 302
  force = true

[[redirects]]
  from = "/about"
  to = "/en/about/"
  status = 302
  force = true

[[redirects]]
  from = "/privacy"
  to = "/es/privacy/"
  status = 302
  force = true

[[redirects]]
  from = "/privacy"
  to = "/en/privacy/"
  status = 302
  force = true

[[redirects]]
  from = "/contact"
  to = "/es/contact/"
  status = 302
  force = true

[[redirects]]
  from = "/contact"
  to = "/en/contact/"
  status = 302
  force = true

# Redirecciones para manejar rutas de blog
[[redirects]]
  from = "/blog/*"
  to = "/es/blog/:splat/"
  status = 302
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/en/blog/:splat/"
  status = 302
  force = true

# Redirecciones para páginas específicas
[[redirects]]
  from = "/contact*"
  to = "/es/contact/"
  status = 301
  force = true

[[redirects]]
  from = "/funciones-4*"
  to = "/es/features/"
  status = 301
  force = true

[[redirects]]
  from = "/pantalla-de-metodo*"
  to = "/es/method/"
  status = 301
  force = true

[[redirects]]
  from = "/pantalla-de-inicio*"
  to = "/es/dashboard/"
  status = 301
  force = true

[[redirects]]
  from = "/conoce*"
  to = "/es/about/"
  status = 301
  force = true

[[redirects]]
  from = "/curso/cronometras-app*"
  to = "/es/features/"
  status = 301
  force = true

[[redirects]]
  from = "/author/micaot*"
  to = "/es/about/"
  status = 301
  force = true

[[redirects]]
  from = "/faq*"
  to = "/es/faq/"
  status = 301
  force = true

[[redirects]]
  from = "/pantalla-de-cronometraje*"
  to = "/es/repetitive/"
  status = 301
  force = true

# Redirecciones para URLs con espacios (%20) a URLs con guiones (-) en el blog
[[redirects]]
  from = "/es/blog/*%20*"
  to = "/es/blog/:splat1-:splat2/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2"}

# Redirecciones para URLs antiguas sin prefijo de idioma
[[redirects]]
  from = "/blog/*%20*"
  to = "/es/blog/:splat1-:splat2/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2"}

[[redirects]]
  from = "/*%20*"
  to = "/es/blog/:splat1-:splat2/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2"}

[[redirects]]
  from = "/en/blog/*%20*"
  to = "/en/blog/:splat1-:splat2/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2"}

# Redirección para URLs con múltiples espacios
[[redirects]]
  from = "/es/blog/*%20*%20*"
  to = "/es/blog/:splat1-:splat2-:splat3/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2", splat3 = ":splat3"}

[[redirects]]
  from = "/blog/*%20*%20*"
  to = "/es/blog/:splat1-:splat2-:splat3/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2", splat3 = ":splat3"}

[[redirects]]
  from = "/*%20*%20*"
  to = "/es/blog/:splat1-:splat2-:splat3/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2", splat3 = ":splat3"}

[[redirects]]
  from = "/en/blog/*%20*%20*"
  to = "/en/blog/:splat1-:splat2-:splat3/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2", splat3 = ":splat3"}

# Redirección para URLs con aún más espacios
[[redirects]]
  from = "/es/blog/*%20*%20*%20*"
  to = "/es/blog/:splat1-:splat2-:splat3-:splat4/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2", splat3 = ":splat3", splat4 = ":splat4"}

[[redirects]]
  from = "/en/blog/*%20*%20*%20*"
  to = "/en/blog/:splat1-:splat2-:splat3-:splat4/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2", splat3 = ":splat3", splat4 = ":splat4"}

# Redirección para URLs con cinco palabras
[[redirects]]
  from = "/es/blog/*%20*%20*%20*%20*"
  to = "/es/blog/:splat1-:splat2-:splat3-:splat4-:splat5/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2", splat3 = ":splat3", splat4 = ":splat4", splat5 = ":splat5"}

[[redirects]]
  from = "/en/blog/*%20*%20*%20*%20*"
  to = "/en/blog/:splat1-:splat2-:splat3-:splat4-:splat5/"
  status = 301
  force = true
  query = {splat1 = ":splat1", splat2 = ":splat2", splat3 = ":splat3", splat4 = ":splat4", splat5 = ":splat5"}

# Asegurarse de que las rutas de API funcionen
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Redirección fallback para SPA
[[redirects]]
  from = "/*"
  to = "/es/404/"
  status = 404