[build]
  command = "bash netlify-build.sh"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones para manejar rutas con lenguaje
[[redirects]]
  from = "/"
  to = "/es/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es/"
  status = 302
  force = true

# Redirecciones para páginas específicas
[[redirects]]
  from = "/about"
  to = "/es/about/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/about"
  to = "/en/about/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/privacy"
  to = "/es/privacy/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/privacy"
  to = "/en/privacy/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/contact"
  to = "/es/contact/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/contact"
  to = "/en/contact/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

# Redirecciones para manejar rutas de blog
[[redirects]]
  from = "/blog/*"
  to = "/es/blog/:splat/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/blog/*"
  to = "/en/blog/:splat/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

# Redirecciones 301 para artículos del blog antiguo (con dominio completo)
[[redirects]]
  from = "https://cronometras.com/*"
  to = "https://cronometras-blog.netlify.app/:splat"
  status = 301
  force = true

# Redirecciones 301 para artículos del blog antiguo - Regla genérica
[[redirects]]
  from = "/:article"
  to = "/es/blog/:article/"
  status = 301
  force = true
  conditions = {Article = ["calculo-de-saturacion-en-un-estudio-de-tiempos", "balanceo-de-lineas-optimizando-la-eficiencia-en-procesos-de-manufactura", "como-se-realiza-un-estudio-de-tiempos-y-movimientos-con-cronometro", "por-que-hay-retrasos-en-la-produccion", "muestreo-del-trabajo", "que-es-el-estudio-de-tiempos-y-movimientos", "que-tipos-de-cronometros-existen", "que-es-gsd-en-ingenieria", "la-utilidad-de-los-tiempos-historicos-para-establecer-estandares-de-trabajo", "que-es-el-cronometraje-industrial", "cuales-son-las-tecnicas-de-cronometraje-industrial", "cuales-son-las-fases-de-un-proceso-industrial", "el-estudio-del-trabajo", "etapas-del-estudio-de-tiempos-en-un-cronometraje-industrial", "metodos-y-tiempos-en-la-gestion-empresarial-industrial", "numero-de-observaciones-a-realizar-en-un-cronometraje-industrial", "objetivos-del-estudio-del-trabajo", "sistema-bedaux", "como-reducir-el-tiempo-de-entrega-para-mejorar-la-productividad-competitividad-y-eficiencia-de-su-empresa", "optimizacion-de-sistemas-productivos-clave-para-la-eficiencia-industrial", "herramientas-necesarias-para-realizar-un-estudio-de-tiempos", "obeya-room-lean", "takt-time-que-es-como-se-calcula-y-como-se-aplica", "la-apreciacion-de-la-actividad-en-el-cronometraje-industrial", "como-estandarizar-los-tiempos-de-trabajo-en-la-industria", "cronometraje-y-la-estandarizacion-de-procesos", "la-importancia-del-estudio-de-tiempos-de-trabajo", "beneficios-y-desafios-de-implementar-el-lean-manufacturing-en-su-empresa", "productividad-empresarial-con-control-de-tiempos-y-el-cronometraje-industrial", "la-ergonomia-del-dolor-a-la-productividad"]}

# Redirecciones 301 para artículos del blog antiguo con barra diagonal al final
[[redirects]]
  from = "/:article/"
  to = "/es/blog/:article/"
  status = 301
  force = true
  conditions = {Article = ["calculo-de-saturacion-en-un-estudio-de-tiempos", "balanceo-de-lineas-optimizando-la-eficiencia-en-procesos-de-manufactura", "como-se-realiza-un-estudio-de-tiempos-y-movimientos-con-cronometro", "por-que-hay-retrasos-en-la-produccion", "muestreo-del-trabajo", "que-es-el-estudio-de-tiempos-y-movimientos", "que-tipos-de-cronometros-existen", "que-es-gsd-en-ingenieria", "la-utilidad-de-los-tiempos-historicos-para-establecer-estandares-de-trabajo", "que-es-el-cronometraje-industrial", "cuales-son-las-tecnicas-de-cronometraje-industrial", "cuales-son-las-fases-de-un-proceso-industrial", "el-estudio-del-trabajo", "etapas-del-estudio-de-tiempos-en-un-cronometraje-industrial", "metodos-y-tiempos-en-la-gestion-empresarial-industrial", "numero-de-observaciones-a-realizar-en-un-cronometraje-industrial", "objetivos-del-estudio-del-trabajo", "sistema-bedaux", "como-reducir-el-tiempo-de-entrega-para-mejorar-la-productividad-competitividad-y-eficiencia-de-su-empresa", "optimizacion-de-sistemas-productivos-clave-para-la-eficiencia-industrial", "herramientas-necesarias-para-realizar-un-estudio-de-tiempos", "obeya-room-lean", "takt-time-que-es-como-se-calcula-y-como-se-aplica", "la-apreciacion-de-la-actividad-en-el-cronometraje-industrial", "como-estandarizar-los-tiempos-de-trabajo-en-la-industria", "cronometraje-y-la-estandarizacion-de-procesos", "la-importancia-del-estudio-de-tiempos-de-trabajo", "beneficios-y-desafios-de-implementar-el-lean-manufacturing-en-su-empresa", "productividad-empresarial-con-control-de-tiempos-y-el-cronometraje-industrial", "la-ergonomia-del-dolor-a-la-productividad"]}

# Asegurarse de que las rutas de API funcionen
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirección fallback para SPA
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404