[build]
  command = "bash netlify-build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  # Añadir esta variable para mostrar más información durante la construcción
  NETLIFY_VERBOSE = "true"

# Redirecciones para manejar rutas con lenguaje
[[redirects]]
  from = "/"
  to = "/es"
  status = 302
  force = false
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = false
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 302

# Redirecciones para páginas específicas
[[redirects]]
  from = "/about"
  to = "/es/about"
  status = 302
  force = false
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/about"
  to = "/en/about"
  status = 302
  force = false
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/privacy"
  to = "/es/privacy"
  status = 302
  force = false
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/privacy"
  to = "/en/privacy"
  status = 302
  force = false
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/contact"
  to = "/es/contacto"
  status = 302
  force = false
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/contact"
  to = "/en/contact"
  status = 302
  force = false
  conditions = {Language = ["en"]}

# Redirección fallback para SPA
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Agregar encabezados de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com; font-src 'self'; frame-src 'self'; object-src 'none'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 