[build]
  command = "bash netlify-build.sh"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones prioritarias para artículos del blog con problemas
[[redirects]]
  from = "/balanceo-de-lineas-optimizando-la-eficiencia-en-procesos-de-manufactura*"
  to = "/es/blog/balanceo-de-lineas-optimizando-la-eficiencia-en-procesos-de-manufactura/"
  status = 301
  force = true
  priority = 100

[[redirects]]
  from = "/calculo-de-saturacion-en-un-estudio-de-tiempos*"
  to = "/es/blog/calculo-de-saturacion-en-un-estudio-de-tiempos/"
  status = 301
  force = true
  priority = 100

[[redirects]]
  from = "/que-es-el-cronometraje-industrial*"
  to = "/es/blog/que-es-el-cronometraje-industrial/"
  status = 301
  force = true
  priority = 100

[[redirects]]
  from = "/cuales-son-las-tecnicas-de-cronometraje-industrial*"
  to = "/es/blog/cuales-son-las-tecnicas-de-cronometraje-industrial/"
  status = 301
  force = true
  priority = 100

# Redirecciones para manejar rutas con lenguaje
[[redirects]]
  from = "/"
  to = "/es/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es/"
  status = 302
  force = true

# Redirecciones para páginas específicas
[[redirects]]
  from = "/about"
  to = "/es/about/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/about"
  to = "/en/about/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/privacy"
  to = "/es/privacy/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/privacy"
  to = "/en/privacy/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/contact"
  to = "/es/contact/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/contact"
  to = "/en/contact/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

# Redirecciones para manejar rutas de blog
[[redirects]]
  from = "/blog/*"
  to = "/es/blog/:splat/"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/blog/*"
  to = "/en/blog/:splat/"
  status = 302
  force = true
  conditions = {Language = ["en"]}

# Redirección 301 para la página principal
[[redirects]]
  from = "/"
  to = "/es/"
  status = 301
  force = true

# Redirección 301 para la página de contacto
[[redirects]]
  from = "/contact"
  to = "/es/contact/"
  status = 301
  force = true

[[redirects]]
  from = "/contact/"
  to = "/es/contact/"
  status = 301
  force = true

# Redirección 301 para la página de funciones
[[redirects]]
  from = "/funciones-4"
  to = "/es/features/"
  status = 301
  force = true

[[redirects]]
  from = "/funciones-4/"
  to = "/es/features/"
  status = 301
  force = true

# Redirección 301 para la página de método
[[redirects]]
  from = "/pantalla-de-metodo"
  to = "/es/method/"
  status = 301
  force = true

[[redirects]]
  from = "/pantalla-de-metodo/"
  to = "/es/method/"
  status = 301
  force = true

# Redirección 301 para la página de inicio
[[redirects]]
  from = "/pantalla-de-inicio"
  to = "/es/dashboard/"
  status = 301
  force = true

[[redirects]]
  from = "/pantalla-de-inicio/"
  to = "/es/dashboard/"
  status = 301
  force = true

# Redirección 301 para la página de conoce
[[redirects]]
  from = "/conoce"
  to = "/es/about/"
  status = 301
  force = true

[[redirects]]
  from = "/conoce/"
  to = "/es/about/"
  status = 301
  force = true

# Redirección 301 para la página de curso
[[redirects]]
  from = "/curso/cronometras-app"
  to = "/es/features/"
  status = 301
  force = true

[[redirects]]
  from = "/curso/cronometras-app/"
  to = "/es/features/"
  status = 301
  force = true

# Redirección 301 para la página de autor
[[redirects]]
  from = "/author/micaot"
  to = "/es/about/"
  status = 301
  force = true

[[redirects]]
  from = "/author/micaot/"
  to = "/es/about/"
  status = 301
  force = true

# Redirección 301 para la página de FAQ
[[redirects]]
  from = "/faq"
  to = "/es/faq/"
  status = 301
  force = true

[[redirects]]
  from = "/faq/"
  to = "/es/faq/"
  status = 301
  force = true

# Redirección 301 para la página de cronometraje
[[redirects]]
  from = "/pantalla-de-cronometraje"
  to = "/es/repetitive/"
  status = 301
  force = true

[[redirects]]
  from = "/pantalla-de-cronometraje/"
  to = "/es/repetitive/"
  status = 301
  force = true

# Redirecciones individuales para artículos del blog antiguo

# Redirección para calculo-de-saturacion-en-un-estudio-de-tiempos
# Movida al inicio del archivo con prioridad alta

# Redirección movida al final del archivo

# Redirección para como-se-realiza-un-estudio-de-tiempos-y-movimientos-con-cronometro
[[redirects]]
  from = "/como-se-realiza-un-estudio-de-tiempos-y-movimientos-con-cronometro"
  to = "/es/blog/como-se-realiza-un-estudio-de-tiempos-y-movimientos-con-cronometro/"
  status = 301
  force = true

[[redirects]]
  from = "/como-se-realiza-un-estudio-de-tiempos-y-movimientos-con-cronometro/"
  to = "/es/blog/como-se-realiza-un-estudio-de-tiempos-y-movimientos-con-cronometro/"
  status = 301
  force = true

# Redirección para por-que-hay-retrasos-en-la-produccion
[[redirects]]
  from = "/por-que-hay-retrasos-en-la-produccion"
  to = "/es/blog/por-que-hay-retrasos-en-la-produccion/"
  status = 301
  force = true

[[redirects]]
  from = "/por-que-hay-retrasos-en-la-produccion/"
  to = "/es/blog/por-que-hay-retrasos-en-la-produccion/"
  status = 301
  force = true

# Redirección para muestreo-del-trabajo
[[redirects]]
  from = "/muestreo-del-trabajo"
  to = "/es/blog/muestreo-del-trabajo/"
  status = 301
  force = true

[[redirects]]
  from = "/muestreo-del-trabajo/"
  to = "/es/blog/muestreo-del-trabajo/"
  status = 301
  force = true

# Redirección para que-es-el-estudio-de-tiempos-y-movimientos
[[redirects]]
  from = "/que-es-el-estudio-de-tiempos-y-movimientos"
  to = "/es/blog/que-es-el-estudio-de-tiempos-y-movimientos/"
  status = 301
  force = true

[[redirects]]
  from = "/que-es-el-estudio-de-tiempos-y-movimientos/"
  to = "/es/blog/que-es-el-estudio-de-tiempos-y-movimientos/"
  status = 301
  force = true

# Redirección para que-tipos-de-cronometros-existen
[[redirects]]
  from = "/que-tipos-de-cronometros-existen"
  to = "/es/blog/que-tipos-de-cronometros-existen/"
  status = 301
  force = true

[[redirects]]
  from = "/que-tipos-de-cronometros-existen/"
  to = "/es/blog/que-tipos-de-cronometros-existen/"
  status = 301
  force = true

# Redirección para que-es-gsd-en-ingenieria
[[redirects]]
  from = "/que-es-gsd-en-ingenieria"
  to = "/es/blog/que-es-gsd-en-ingenieria/"
  status = 301
  force = true

[[redirects]]
  from = "/que-es-gsd-en-ingenieria/"
  to = "/es/blog/que-es-gsd-en-ingenieria/"
  status = 301
  force = true

# Redirección para la-utilidad-de-los-tiempos-historicos-para-establecer-estandares-de-trabajo
[[redirects]]
  from = "/la-utilidad-de-los-tiempos-historicos-para-establecer-estandares-de-trabajo"
  to = "/es/blog/la-utilidad-de-los-tiempos-historicos-para-establecer-estandares-de-trabajo/"
  status = 301
  force = true

[[redirects]]
  from = "/la-utilidad-de-los-tiempos-historicos-para-establecer-estandares-de-trabajo/"
  to = "/es/blog/la-utilidad-de-los-tiempos-historicos-para-establecer-estandares-de-trabajo/"
  status = 301
  force = true

# Redirección para que-es-el-cronometraje-industrial
# Movida al inicio del archivo con prioridad alta

# Redirección para cuales-son-las-tecnicas-de-cronometraje-industrial
# Movida al inicio del archivo con prioridad alta

# Redirección para cuales-son-las-fases-de-un-proceso-industrial
[[redirects]]
  from = "/cuales-son-las-fases-de-un-proceso-industrial"
  to = "/es/blog/cuales-son-las-fases-de-un-proceso-industrial/"
  status = 301
  force = true

[[redirects]]
  from = "/cuales-son-las-fases-de-un-proceso-industrial/"
  to = "/es/blog/cuales-son-las-fases-de-un-proceso-industrial/"
  status = 301
  force = true

# Redirección para el-estudio-del-trabajo
[[redirects]]
  from = "/el-estudio-del-trabajo"
  to = "/es/blog/el-estudio-del-trabajo/"
  status = 301
  force = true

[[redirects]]
  from = "/el-estudio-del-trabajo/"
  to = "/es/blog/el-estudio-del-trabajo/"
  status = 301
  force = true

# Redirección para etapas-del-estudio-de-tiempos-en-un-cronometraje-industrial
[[redirects]]
  from = "/etapas-del-estudio-de-tiempos-en-un-cronometraje-industrial"
  to = "/es/blog/etapas-del-estudio-de-tiempos-en-un-cronometraje-industrial/"
  status = 301
  force = true

[[redirects]]
  from = "/etapas-del-estudio-de-tiempos-en-un-cronometraje-industrial/"
  to = "/es/blog/etapas-del-estudio-de-tiempos-en-un-cronometraje-industrial/"
  status = 301
  force = true

# Redirección para metodos-y-tiempos-en-la-gestion-empresarial-industrial
[[redirects]]
  from = "/metodos-y-tiempos-en-la-gestion-empresarial-industrial"
  to = "/es/blog/metodos-y-tiempos-en-la-gestion-empresarial-industrial/"
  status = 301
  force = true

[[redirects]]
  from = "/metodos-y-tiempos-en-la-gestion-empresarial-industrial/"
  to = "/es/blog/metodos-y-tiempos-en-la-gestion-empresarial-industrial/"
  status = 301
  force = true

# Redirección para numero-de-observaciones-a-realizar-en-un-cronometraje-industrial
[[redirects]]
  from = "/numero-de-observaciones-a-realizar-en-un-cronometraje-industrial"
  to = "/es/blog/numero-de-observaciones-a-realizar-en-un-cronometraje-industrial/"
  status = 301
  force = true

[[redirects]]
  from = "/numero-de-observaciones-a-realizar-en-un-cronometraje-industrial/"
  to = "/es/blog/numero-de-observaciones-a-realizar-en-un-cronometraje-industrial/"
  status = 301
  force = true

# Redirección para objetivos-del-estudio-del-trabajo
[[redirects]]
  from = "/objetivos-del-estudio-del-trabajo"
  to = "/es/blog/objetivos-del-estudio-del-trabajo/"
  status = 301
  force = true

[[redirects]]
  from = "/objetivos-del-estudio-del-trabajo/"
  to = "/es/blog/objetivos-del-estudio-del-trabajo/"
  status = 301
  force = true

# Redirección para sistema-bedaux
[[redirects]]
  from = "/sistema-bedaux"
  to = "/es/blog/sistema-bedaux/"
  status = 301
  force = true

[[redirects]]
  from = "/sistema-bedaux/"
  to = "/es/blog/sistema-bedaux/"
  status = 301
  force = true

# Redirección para como-reducir-el-tiempo-de-entrega-para-mejorar-la-productividad-competitividad-y-eficiencia-de-su-empresa
[[redirects]]
  from = "/como-reducir-el-tiempo-de-entrega-para-mejorar-la-productividad-competitividad-y-eficiencia-de-su-empresa"
  to = "/es/blog/como-reducir-el-tiempo-de-entrega-para-mejorar-la-productividad-competitividad-y-eficiencia-de-su-empresa/"
  status = 301
  force = true

[[redirects]]
  from = "/como-reducir-el-tiempo-de-entrega-para-mejorar-la-productividad-competitividad-y-eficiencia-de-su-empresa/"
  to = "/es/blog/como-reducir-el-tiempo-de-entrega-para-mejorar-la-productividad-competitividad-y-eficiencia-de-su-empresa/"
  status = 301
  force = true

# Redirección para optimizacion-de-sistemas-productivos-clave-para-la-eficiencia-industrial
[[redirects]]
  from = "/optimizacion-de-sistemas-productivos-clave-para-la-eficiencia-industrial"
  to = "/es/blog/optimizacion-de-sistemas-productivos-clave-para-la-eficiencia-industrial/"
  status = 301
  force = true

[[redirects]]
  from = "/optimizacion-de-sistemas-productivos-clave-para-la-eficiencia-industrial/"
  to = "/es/blog/optimizacion-de-sistemas-productivos-clave-para-la-eficiencia-industrial/"
  status = 301
  force = true

# Redirección para herramientas-necesarias-para-realizar-un-estudio-de-tiempos
[[redirects]]
  from = "/herramientas-necesarias-para-realizar-un-estudio-de-tiempos"
  to = "/es/blog/herramientas-necesarias-para-realizar-un-estudio-de-tiempos/"
  status = 301
  force = true

[[redirects]]
  from = "/herramientas-necesarias-para-realizar-un-estudio-de-tiempos/"
  to = "/es/blog/herramientas-necesarias-para-realizar-un-estudio-de-tiempos/"
  status = 301
  force = true

# Redirección para obeya-room-lean
[[redirects]]
  from = "/obeya-room-lean"
  to = "/es/blog/obeya-room-lean/"
  status = 301
  force = true

[[redirects]]
  from = "/obeya-room-lean/"
  to = "/es/blog/obeya-room-lean/"
  status = 301
  force = true

# Redirección para takt-time-que-es-como-se-calcula-y-como-se-aplica
[[redirects]]
  from = "/takt-time-que-es-como-se-calcula-y-como-se-aplica"
  to = "/es/blog/takt-time-que-es-como-se-calcula-y-como-se-aplica/"
  status = 301
  force = true

[[redirects]]
  from = "/takt-time-que-es-como-se-calcula-y-como-se-aplica/"
  to = "/es/blog/takt-time-que-es-como-se-calcula-y-como-se-aplica/"
  status = 301
  force = true

# Redirección para la-apreciacion-de-la-actividad-en-el-cronometraje-industrial
[[redirects]]
  from = "/la-apreciacion-de-la-actividad-en-el-cronometraje-industrial"
  to = "/es/blog/la-apreciacion-de-la-actividad-en-el-cronometraje-industrial/"
  status = 301
  force = true

[[redirects]]
  from = "/la-apreciacion-de-la-actividad-en-el-cronometraje-industrial/"
  to = "/es/blog/la-apreciacion-de-la-actividad-en-el-cronometraje-industrial/"
  status = 301
  force = true

# Redirección para como-estandarizar-los-tiempos-de-trabajo-en-la-industria
[[redirects]]
  from = "/como-estandarizar-los-tiempos-de-trabajo-en-la-industria"
  to = "/es/blog/como-estandarizar-los-tiempos-de-trabajo-en-la-industria/"
  status = 301
  force = true

[[redirects]]
  from = "/como-estandarizar-los-tiempos-de-trabajo-en-la-industria/"
  to = "/es/blog/como-estandarizar-los-tiempos-de-trabajo-en-la-industria/"
  status = 301
  force = true

# Redirección para cronometraje-y-la-estandarizacion-de-procesos
[[redirects]]
  from = "/cronometraje-y-la-estandarizacion-de-procesos"
  to = "/es/blog/cronometraje-y-la-estandarizacion-de-procesos/"
  status = 301
  force = true

[[redirects]]
  from = "/cronometraje-y-la-estandarizacion-de-procesos/"
  to = "/es/blog/cronometraje-y-la-estandarizacion-de-procesos/"
  status = 301
  force = true

# Redirección para la-importancia-del-estudio-de-tiempos-de-trabajo
[[redirects]]
  from = "/la-importancia-del-estudio-de-tiempos-de-trabajo"
  to = "/es/blog/la-importancia-del-estudio-de-tiempos-de-trabajo/"
  status = 301
  force = true

[[redirects]]
  from = "/la-importancia-del-estudio-de-tiempos-de-trabajo/"
  to = "/es/blog/la-importancia-del-estudio-de-tiempos-de-trabajo/"
  status = 301
  force = true

# Redirección para beneficios-y-desafios-de-implementar-el-lean-manufacturing-en-su-empresa
[[redirects]]
  from = "/beneficios-y-desafios-de-implementar-el-lean-manufacturing-en-su-empresa"
  to = "/es/blog/beneficios-y-desafios-de-implementar-el-lean-manufacturing-en-su-empresa/"
  status = 301
  force = true

[[redirects]]
  from = "/beneficios-y-desafios-de-implementar-el-lean-manufacturing-en-su-empresa/"
  to = "/es/blog/beneficios-y-desafios-de-implementar-el-lean-manufacturing-en-su-empresa/"
  status = 301
  force = true

# Redirección para productividad-empresarial-con-control-de-tiempos-y-el-cronometraje-industrial
[[redirects]]
  from = "/productividad-empresarial-con-control-de-tiempos-y-el-cronometraje-industrial"
  to = "/es/blog/productividad-empresarial-con-control-de-tiempos-y-el-cronometraje-industrial/"
  status = 301
  force = true

[[redirects]]
  from = "/productividad-empresarial-con-control-de-tiempos-y-el-cronometraje-industrial/"
  to = "/es/blog/productividad-empresarial-con-control-de-tiempos-y-el-cronometraje-industrial/"
  status = 301
  force = true

# Redirección para la-ergonomia-del-dolor-a-la-productividad
[[redirects]]
  from = "/la-ergonomia-del-dolor-a-la-productividad"
  to = "/es/blog/la-ergonomia-del-dolor-a-la-productividad/"
  status = 301
  force = true

[[redirects]]
  from = "/la-ergonomia-del-dolor-a-la-productividad/"
  to = "/es/blog/la-ergonomia-del-dolor-a-la-productividad/"
  status = 301
  force = true

# Redirección para balanceo-de-lineas-optimizando-la-eficiencia-en-procesos-de-manufactura
# Movida al inicio del archivo con prioridad alta

# Asegurarse de que las rutas de API funcionen
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirección fallback para SPA
[[redirects]]
  from = "/*"
  to = "/es/404/"
  status = 404